### ISSUE TITLE
unable to scan deposit qr code from muun wallet

### ISSUE THREAD

**Issue by neb-b** [joinmarket-webui/joinmarket-webui#164] opened 2022-03-08 18:04 UTC
Maybe this is a muun issue? (I only tried muun and strike, and strike works)

When scanning the qr code I see this error
![IMG_0022](https://user-images.githubusercontent.com/16882830/157298460-7e9b9ec6-c143-47f9-9123-b797f41847e8.PNG)

**Comment by theborakompanioni** [comment] 2022-03-08 18:52
This might be a duplicate of #145  which is fixed by #146. 
I wonder about the escaped colon (`%A3`), though - that is displayed differently in the referenced issue, which was reportedly also done with Muun.
If it is able to scan the following codes successfully (payment to genesis block coinbase address), then it should be fixed in the next release.

`bitcoin:1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa`
<img src="https://user-images.githubusercontent.com/3358649/157304195-673b2936-98ec-419c-ab8e-9d583d8897ef.png" width=260 />
`bitcoin:1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa?amount=50.00000000`
<img src="https://user-images.githubusercontent.com/3358649/157304520-7071b15f-ccab-4a54-9d12-4029f494b3f0.png" width=260 />

Can someone don't trust and verify?

**Comment by neb-b** [comment] 2022-03-08 22:30
Yeah I wasn't sure about the `%A3` 

Both of those qr codes are able to be scanned by muun for me

**Closed** 2022-03-08 22:30 UTC
